# Generated by Django 4.2 on 2024-10-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Статус публикации"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                default="#", editable=False, max_length=200, verbose_name="Слаг"
            ),
        ),
    ]
