# Generated by Django 5.1.1 on 2024-10-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_sender", "0002_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_mailing",
            field=models.DateTimeField(verbose_name="Дата и время начала рассылки"),
        ),
    ]
