# Generated by Django 5.1.1 on 2024-10-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0003_alter_mailing_start_mailing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Massage',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='massage',
            new_name='message',
        ),
    ]
