# Generated by Django 5.1.1 on 2024-10-08 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0004_rename_massage_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
